# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product_desc', models.CharField(max_length=250, verbose_name='Product Description')),
                ('product_image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Product Image')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Product Price')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
